version: '3'
services:
  react-docker:
    build:
      context: ./ # same build .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app # . is root project
    restart: always